# Can NOT install apache-arrow on the amazonlinux:2023-minimal image,
# so install the ruby directly on amazonlinux:2023.
FROM public.ecr.aws/amazonlinux/amazonlinux:2023

# Apache Arrow
ARG ARROW_VERSION=19.0.1
RUN dnf upgrade -y --releasever=latest \
  && dnf install -y https://apache.jfrog.io/artifactory/arrow/amazon-linux/2023/x86_64/Packages/apache-arrow-release-${ARROW_VERSION}-1.amzn2023.noarch.rpm \
  && dnf install -y arrow-devel arrow-glib-devel arrow-dataset-devel arrow-dataset-glib-devel \
  && dnf clean all

RUN dnf upgrade -y --releasever=latest \
  && dnf install -y git gcc gcc-c++ readline-devel openssl-devel libyaml-devel zlib-devel \
  && dnf clean all

# Install Ruby and AWS Lambda Ruby Runtime Interface Client
ARG RUBY_VERSION=3.3.7
ARG RUBY_MINOR_VERSION=3.3
RUN mkdir -p /tmp/src \
  && cd /tmp/src \
  && curl -O https://cache.ruby-lang.org/pub/ruby/${RUBY_MINOR_VERSION}/ruby-${RUBY_VERSION}.tar.gz \
  && tar zxvf ruby-${RUBY_VERSION}.tar.gz \
  && cd ruby-${RUBY_VERSION} \
  && ./configure \
  && make \
  && make install \
  && gem install bundler \
  && rm -fr $PWD
RUN gem install aws_lambda_ric
ENV LAMBDA_RUNTIME_DIR=/var/runtime LAMBDA_TASK_ROOT=/var/task
WORKDIR $LAMBDA_TASK_ROOT

# Update bundler
RUN gem update bundler

# Install gems
COPY Gemfile Gemfile.lock athena-udf.gemspec ${LAMBDA_TASK_ROOT}
COPY lib/athena-udf/version.rb ${LAMBDA_TASK_ROOT}/lib/athena-udf/version.rb
ENV GEM_HOME=${LAMBDA_TASK_ROOT}
RUN bundle config set --local without development:test \
  && bundle install

COPY . ${LAMBDA_TASK_ROOT}
COPY docker/lambda-entrypoint.sh /

ENTRYPOINT ["/lambda-entrypoint.sh"]
CMD ["example.SimpleVarcharUDF.lambda_handler"]

