FROM public.ecr.aws/lambda/ruby:3.3-x86_64

# Standard dnf is necessary to install Apache Arrow.
RUN microdnf upgrade -y --releasever=latest \
  && microdnf remove -y microdnf-dnf \
  && microdnf install -y dnf \
  && microdnf clean all

RUN dnf upgrade -y --releasever=latest \
  && dnf install -y git \
  && dnf clean all

# Apache Arrow
ARG ARROW_VERSION=19.0.1
RUN dnf upgrade -y --releasever=latest \
  && dnf install -y https://apache.jfrog.io/artifactory/arrow/amazon-linux/2023/x86_64/Packages/apache-arrow-release-${ARROW_VERSION}-1.amzn2023.noarch.rpm \
  && dnf install -y arrow-devel arrow-glib-devel arrow-dataset-devel arrow-dataset-glib-devel \
  && dnf clean all

# Update bundler
RUN gem update bundler

# Install gems
COPY Gemfile Gemfile.lock athena-udf.gemspec ${LAMBDA_TASK_ROOT}
COPY lib/athena-udf/version.rb ${LAMBDA_TASK_ROOT}/lib/athena-udf/version.rb
ENV GEM_HOME=${LAMBDA_TASK_ROOT}
RUN bundle config set --local without development:test \
  && bundle install

COPY . ${LAMBDA_TASK_ROOT}

ENV RUBY_YJIT_ENABLE=1
CMD ["example.SimpleVarcharUDF.lambda_handler"]

